### ISSUE TITLE
About "dependency.srcAccessMask = 0;" question

### ISSUE THREAD

**Issue by flowerdancedatou** [ARM-software/vulkan-sdk#14]
I hava a question about "srcAccessMask = 0".  Is  it say "can't read and write"?

**Comment by AttilioProvenzano-ARM** [comment]
Hi @flowerdancedatou, 

This is an external subpass dependency which binds to the acquisition semaphore for the swapchain image. The subpass performs an implicit transition from `VK_IMAGE_LAYOUT_UNDEFINED` -> `VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL` and we need to ensure that the image has been acquired when that transition happens.

The acquisition semaphore's `pWaitDstStageMask` guarantees that the image acquisition will happen before `VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT`, but we don't know exactly when. Thus we need an external dependency which fixes the stage for the transition to `VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT`, otherwise the GPU might try to transition the image before it is acquired from the presentation engine.

Regarding `srcAccessMask = 0`, it refers to the access scope before the transition happens. Since we are not doing reading/writing the image before the transition (it comes from the presentation engine and it's in `VK_IMAGE_LAYOUT_UNDEFINED`, so we can't do anything with it), it makes sense for the `srcAccessMask` to be 0.

Hope that helps!

**Comment by flowerdancedatou** [comment]
@AttilioProvenzano-ARM  Thank you very much.

**Comment by isbdnt** [comment]
From my understanding, normally, I should set dependency.srcAccessMask = VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT, but in this case, the image is acquired from presentation engine, the accesses are always visible, so I can safely let it be 0, is it right?

**Comment by isbdnt** [comment]
From my understanding, srcAccessMask = 0 is a special case, it means the first synchronization scope includes all operations in srcStageMask. If you let srcAccessMask = VK_ACCESS_COLOR_ATTACHMENT_READ_BIT, then it means the first synchronization scope includes only read operations in srcStageMask. [reference to synchronization scope](https://www.khronos.org/registry/vulkan/specs/1.2-khr-extensions/html/chap7.html#synchronization-pipeline-stages)
