### ISSUE TITLE
About the num of  multisampledRenderTargets in the sample that is named "Multisampling in Vulkan".

### ISSUE THREAD

**Issue by flowerdancedatou** [ARM-software/vulkan-sdk#17]
Why  only have one multisampledRenderTarget  that is used to rendering？  Why not it is  the number of mulitsampledRenderTargets   that is  euqal to  the number of swapchians  to  avoids all hazards of  "Asynchronous GPU"?

**Comment by flowerdancedatou** [comment]
the   depth image in the sample that  is named "Spinning Cube with Depth Testing and Push Constants"  is also.

**Comment by AttilioProvenzano-ARM** [comment]
Hi!

This is due to an optimization for tiled GPUs when you have an attachment that will only be used in a single render pass and doesn't need to be stored. Taking the multisampled render target as an example:

```
// This image will only be used as a transient render target.
// Its purpose is only to hold the multisampled data before resolving the render pass.
info.usage = VK_IMAGE_USAGE_TRANSIENT_ATTACHMENT_BIT | VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT;

[...]

alloc.memoryTypeIndex =
    findMemoryTypeFromRequirementsWithFallback(memReqs.memoryTypeBits, VK_MEMORY_PROPERTY_LAZILY_ALLOCATED_BIT);
```

With a usage of `TRANSIENT_ATTACHMENT_BIT` and a memory type with `LAZILY_ALLOCATED_BIT` the GPU can avoid allocating the image at all, the data will only reside in tile-local memory.
At the end of the render pass the multisampled data are resolved to the swapchain image (see `pResolveAttachments`).

Using the multisampled image doesn't involve any actual memory accesses, so we can use the same one for all framebuffers without hazards.

The same reasoning applies to the depth image you mentioned - it's only used in that render pass and never stored, so we can avoid allocating it at all.

This optimization saves a significant amount of memory bandwidth, you can find more information in the tutorial: https://arm-software.github.io/vulkan-sdk/multisampling.html

Hope that helps! I know it's a tricky subject, so feel free to ask more questions if you need clarifications. :)

Cheers,
Attilio

**Comment by flowerdancedatou** [comment]
Thank you very much. Aha
