### ISSUE TITLE
If I hava uniform buffer that will be updated by dynamic,  I hope not  need   3x uniform. How do?

### ISSUE THREAD

**Issue by flowerdancedatou** [ARM-software/vulkan-sdk#20]
If I hava uniform buffer that will be updated by dynamic,  I hope not  need   3x uniform. How do?

I think I can use some barriers to avoid this problem.

**Comment by AttilioProvenzano-ARM** [comment]
Hi,
If the buffer will be dynamically updated, you will need the 3x uniform buffers (or a single dynamic uniform buffer with 3x the size).

Since you cannot update a part of a buffer that is in use, pipeline barriers won't help: if you have a single buffer, the update on the CPU side will have to wait for the GPU to finish using the buffer, so you would end up serializing frames.

**Comment by flowerdancedatou** [comment]
@AttilioProvenzano-ARM  Thank you very much!
