### ISSUE TITLE
I  hava a problem about  barrier scope. Can you help me?

### ISSUE THREAD

**Issue by flowerdancedatou** [ARM-software/vulkan-sdk#26]
///////////  A set of commands
vkCmd..(…)
…
vkCmd.. (…)
////////////

///////Barrier1
vkCmdPipelineBarrier (…)
///////

///////// B set of commands
vkCmd…(…)
…
vkQueueSubmit(…)
vkQueuePresentKHR(..)
//////////

/////////Barrier2
vkCmdPipelineBarrier (…) 
////////

//////C  set of commands
vkCmd…(…)
…
vkQueueSubmit(…)
vkQueuePresentKHR(..)
//////

I use one queue to submit commands.

I  want to know:

Do the "Barrier1"    act on  "B set of commands" and "Barrier2" and "C  set of commands"?

Thanks you!

**Comment by AttilioProvenzano-ARM** [comment]
Hi,

A pipeline barrier always acts on two sets of commands, those which come before the barrier and those which come after.

Since you don't mention render passes I'm assuming the calls to `vkCmdPipelineBarrier` are outside of a render pass instances. The spec says:
> If vkCmdPipelineBarrier is called outside a render pass instance, then the first set of commands is all prior commands submitted to the queue and recorded in the command buffer and the second set of commands is all subsequent commands recorded in the command buffer and submitted to the queue.

The main difference between the two barriers is that the first one is in the middle of a command buffer, while the second one is after the first commands are submitted and presented (so it is likely to be in another command buffer).
This difference does not really matter according to the spec, because commands previously submitted and previously recorded in the current command buffer are treated the same way.

This is a breakdown of the 2 barriers:
- Barrier1
  - before: set A and everything that comes prior to that
  - after: sets B, C and everything that comes afterwards
- Barrier2
  - before: sets A, B and everything that comes prior to them
  - after: set C and everything that comes afterwards

Hope that helps! :)

**Comment by flowerdancedatou** [comment]
thank you very much!^_^

**Comment by AttilioProvenzano-ARM** [comment]
You can find more information in this blog by Hans-Kristian Arntzen: http://themaister.net/blog/2019/08/14/yet-another-blog-explaining-vulkan-synchronization/

It's quite long and comprehensive, it can help you in fully understanding synchronization. :)
